### ISSUE TITLE
double UCI options in CuteChess GUI ?

### ISSUE THREAD

**Issue by tissatussa** [dede1751/carp#1]
hi, Carp runs fine in CuteChess (v1.2.0 on Linux), but in settings double options are shown :

![carp-double-options](https://user-images.githubusercontent.com/1109281/211881222-91c1338e-3269-4f00-859e-a3d29182c64c.png)

when starting Carp in terminal, it instantly shows its info, like giving the `uci` command .. so maybe this is the cause, i have no clue ..

**Comment by dede1751** [comment]
Hi, thank you for the feedback! I've moved the uci info into the uci command handler and replaced them with a greeting message. This seems to now work properly for me on Cutechess.

**Comment by tissatussa** [comment]
that helped; the CuteChess GUI settings window is normal now !

btw. recently i saw your engine in the new Files section of Darius' https://www.chessengeria.com .. i'm familiar with (the names of) many chess engines, but yours is new to me .. do you have any relation to Darius ?

how strong is Carp anyway ? My tests indicate around 2200 ..

**Comment by dede1751** [comment]
Glad it worked! No, I'm not familiar with him or the forum, it's actually pretty satisfying to see my little project getting a bit of attention, thanks for bringing that up. My engine is really new, I think it's really only out there because I posted about it on Reddit.

As for the rating, it seems to be playing at about that level on Lichess, I've only really had time to test it against Maksim's BBC (1.1 and 1.2, not the nnue versions) and Vice 1.1 over roughly 1000 games, suggesting (albeit with multiple cpus vs their single threads) it's definitely superior.

If you've already tested it, I'd be really happy if you could suggest a few of the engines you used for your tests, for future development. Thanks in advance

**Comment by tissatussa** [comment]
> ..I'm not familiar with him or the forum [..] because I posted about it on Reddit..

the Darius website is rather new, some of its sections are still almost empty / simple .. but that Files section got my attention : supplying (compiled) programs (games and chess engines) is not common, esp. for Linux .. so, it's not a forum, but that might come ?

> ..suggest a few of the engines you used for your tests, for future development..

here's my ZIPped list : 
[my-engine-list.zip](https://github.com/dede1751/carp/files/10404405/my-engine-list.zip)
 it's 98% accurate .. all engines are Linux based, compiled or found assets, most are latest version .. you can pick one and find its source & compile (mostly GitHub), some are hard to find now, otherwise i can send you any Linux binary.

**Comment by dede1751** [comment]
Thank you for the awesome resource! I'll close the issue now but I may contact you privately, you seem very knowledgeable regarding engines.

Definitely not 100% on board with getting straight binaries from websites, but it still seems a potentially nice resource, especially with the M1-only testing.

**Comment by tissatussa** [comment]
roelof@imoma.eu
