### ISSUE TITLE
Carp v2 bad move in end game

### ISSUE THREAD

**Issue by tissatussa** [dede1751/carp#8]
here's another position where Carp fails :
8/N4r2/1p2R3/pP6/1k6/8/8/6K1 w - - 6 50

![carp-plays-Rxb6](https://user-images.githubusercontent.com/1109281/234031323-53be553f-e64a-434d-b6f8-10bdd98aac7c.png)

White to move.
Carp v2.0.0 NNUE plays Rxb6 here, upto very high depth .. but not many engines do, indeed it's a bad move : in the end game White will be lost after Rxa7.

**Comment by tissatussa** [comment]
Carp reaches a high depth (40 an more) within a minute but i wonder how pruning is done .. calculations at high depths seem useless to me when the first moves are 'wrong' ..

**Comment by dede1751** [comment]
Found the bug! This was due to saving incorrect scores to the TT when failing low on a node where quiet moves got pruned. At a very high level, the engine would skip proving the actual existence of a drawing line, and just accept it to be a draw as is in certain positions. This should also fix #3 since it was a similar situation. Removing quiet pruning leads to finding the correct move Nc6. I won't mark this as solved until I actually release the fix, but I am working on a major refactor of Carp's codebase to correct some idiosyncrasies, which will be followed by a search overhaul which will also handle this. Once again, thanks for your efforts!

**Comment by tissatussa** [comment]
Great! I can only imagine how to sense a cause of such errors and find it .. it's your own engine afterall .. after some code changes, were you able to reproduce the bad move(s) ? That's impressive. Good luck with the planned refactoring. For me it was easy to create this Issue, i just had to create a diagram with some words ..

**Comment by dede1751** [comment]
Apparently, I had the culprit wrong, I do not however know how the other approach fixed it. The bug is in the Insufficient Material oracle: 

```rust
match self.board.occupancy.count_bits() {
    2 => true,
    3 => knights | bishops != EMPTY_BB, // 1 knight or 1 bishop
    4 => {
        let one_each = self.board.side_occupancy[0].count_bits() == 2;
        let knight_count = knights.count_bits();
        let bishop_count = bishops.count_bits();
        let king_in_corner = kings & CORNERS != EMPTY_BB;
        let king_on_edge = kings & EDGES != EMPTY_BB;

        (knight_count == 2 && !king_on_edge) || // knvkn, king not on edge
        (bishop_count == 2 && (
            (bishops & WHITE_SQUARES).count_bits() != 1 || // same color bishops
            (one_each && !king_in_corner))) ||  // one bishop each, king not in corner
        (knight_count == bishop_count && one_each && !king_in_corner) // knvkb, king not in corner
    }
    _ => false,
}
```

It's a pretty large oversight that explains both issues: the last condition, giving a draw for king and knight vs king and bishop, ends up actually accepting any pair of pieces if neither player has a bishop or a knight.

**Comment by tissatussa** [comment]
looks nice .. i don't speak Rust, but the syntax highlighting makes me understand a bit .. code should always be tested decently, even small parts : later we MUST rely on a function etc, regardless how complex the rest of the code becomes .. we're all alone while debugging :-)

**Comment by dede1751** [comment]
Both this and #3 fixed [here](https://github.com/dede1751/carp/commit/fb9d80b342fb0d3512fbb51e3d2c94fa45915538), will get closed once Dev is merged to Master when the new version comes out. Probably a while, still not happy with my search.
